name: dockerize

on:
  release: 
    types: [published] 
#    types: [published, created, edited, prereleased, released] 
#  push:
#    tags:
#      - docker*

jobs:
  deploy:
    name: Build and Push Docker
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout CODE
      uses: actions/checkout@v2
      with:
        path: CODE
        
    - name: Copy Dockerfile
      run: cp CODE/docker/Dockerfile Dockerfile

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Dockerize
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: action_demo:latest

